spring:
  application:
    name: EventPass

  logging:
    level:
      root: WARN
      com.BrainBoost.BrainBoost: DEBUG

  datasource:
    url: jdbc:mysql://localhost:3306/EventPass?useSSL=false&serverTimezone=UTC
    username: root
    password: 2004Vit@


  flyway:
    enable: true
    clean-disable: true
    validate-migration-names: true


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
